#!/usr/bin/env bash
echo "Temporarily installing eth-lightwallet"
npm install eth-lightwallet
cd node_modules/eth-lightwallet

echo "Performing bundling"
browserify index.js -o eth-lightwallet.js --node --standalone ethlightwallet

echo "Replacing repo eth-lightwallet.js file with new bundled file"
mv eth-lightwallet.js ../../eth-lightwallet.js
cd ../../

echo "Done! Note: now go through eth-lightwallet.js manually to replace Buffer API usages to newest API"
echo "You may want to run 'npm remove eth-lightwallet' if it is no longer required"
